# Generated by Django 6.0.5 on 2026-05-31 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('credits', models.CharField(choices=[('CREDIT_1_00', '1.00'), ('CREDIT_1_50', '1.50'), ('CREDIT_2_00', '2.00'), ('CREDIT_3_00', '3.00')], default='CREDIT_3_00', max_length=15)),
                ('faculty', models.CharField(default='COMPUTER_SCIENCE_AND_ENGINEERING', max_length=100)),
                ('department', models.CharField(default='COMPUTER_SCIENCE_AND_ENGINEERING', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_active', 'level', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academic.semester')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_infos', to='academic.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_infos', to='academic.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_infos', to='users.teacherprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_infos', to='academic.semester')),
            ],
            options={
                'ordering': ['-semester__is_active', 'course__code'],
                'unique_together': {('course', 'teacher', 'semester', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academic.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
