# Generated by Django 6.0.5 on 2026-05-31 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('QR_ONLINE', 'QR Online'), ('QR_OFFLINE', 'QR Offline')], max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.courseinfo')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=10)),
                ('source', models.CharField(choices=[('HARDWARE', 'Hardware'), ('QR_ONLINE', 'QR Online'), ('QR_OFFLINE', 'QR Offline'), ('MANUAL', 'Manual')], default='MANUAL', max_length=15)),
                ('is_modified_by_teacher', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='academic.courseinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='users.studentprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
